name = "TCSFormalizations"
defaultTargets = ["Sunflower", "SunflowerChecks", "TSPGap", "TSPGapChecks"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[lean_lib]]
name = "Sunflower"

[[lean_lib]]
name = "SunflowerChecks"

[[lean_lib]]
name = "TSPGap"

[lean_lib.leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[lean_lib]]
name = "TSPGapChecks"

[lean_lib.leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
