name = "TCSFormalizations"
defaultTargets = ["Sunflower", "SunflowerChecks"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[lean_lib]]
name = "Sunflower"

[[lean_lib]]
name = "SunflowerChecks"
